# Generated by Django 6.0.2 on 2026-02-09 06:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vynzora_app', '0006_alter_website_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('logo', models.ImageField(upload_to='partners/')),
                ('description', models.TextField(max_length=300)),
                ('point1', models.CharField(max_length=150)),
                ('point2', models.CharField(max_length=150)),
                ('point3', models.CharField(max_length=150)),
                ('point4', models.CharField(max_length=150)),
                ('point5', models.CharField(max_length=150)),
                ('point6', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionalBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main banner title', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle', max_length=300)),
                ('occasion', models.CharField(choices=[('black_friday', 'Black Friday'), ('christmas', 'Christmas'), ('new_year', 'New Year'), ('onam', 'Onam'), ('eid', 'Eid'), ('diwali', 'Diwali'), ('easter', 'Easter'), ('valentine', "Valentine's Day"), ('independence', 'Independence Day'), ('custom', 'Custom Occasion')], default='custom', max_length=50)),
                ('custom_occasion', models.CharField(blank=True, help_text="If 'Custom Occasion' selected", max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('discount_text', models.CharField(help_text="e.g., '80% OFF'", max_length=100)),
                ('offer_description', models.CharField(help_text='Brief offer description', max_length=300)),
                ('show_timer', models.BooleanField(default=True, help_text='Show countdown timer')),
                ('end_date', models.DateTimeField(help_text='Offer expiration date & time')),
                ('background_color', models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color (e.g., #FF5733)', regex='^#([A-Fa-f0-9]{6})$')])),
                ('text_color', models.CharField(default='#FFFFFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color (e.g., #FF5733)', regex='^#([A-Fa-f0-9]{6})$')])),
                ('accent_color', models.CharField(default='#9b59b6', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color (e.g., #FF5733)', regex='^#([A-Fa-f0-9]{6})$')])),
                ('cta_text', models.CharField(default='Claim deal', max_length=100)),
                ('cta_link', models.URLField(help_text='Button destination URL')),
                ('additional_info', models.CharField(blank=True, help_text="Extra info (e.g., '30-day money-back guarantee')", max_length=200)),
                ('priority', models.IntegerField(default=0, help_text='Higher number = higher priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promotional Banner',
                'verbose_name_plural': 'Promotional Banners',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='services/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta_title', models.CharField(blank=True, max_length=70, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=160, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title', max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Train Service',
                'verbose_name_plural': 'Train Services',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='candidate',
            name='cover_letter',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience',
            field=models.CharField(choices=[('0-1 years', '0 to 1 Year'), ('1-3 years', '1 to 3 Years'), ('3-5 years', '3 to 5 Years'), ('5+ years', '5+ Years')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='linkedin_profile',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='portfolio_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume',
            field=models.FileField(default='', upload_to='resumes/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='website',
            name='add_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='main_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='videos',
            field=models.TextField(blank=True, help_text='Add video URLs separated by commas or paste iframe embed codes', null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='job_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='vynzora_app.career_model'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='career_model',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship'), ('contract', 'Contract'), ('remote', 'Remote')], max_length=50),
        ),
        migrations.AlterField(
            model_name='career_model',
            name='post_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='career_model',
            name='posted_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='ServiceProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tagline', models.CharField(max_length=250)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='vynzora_app.services')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='vynzora_app.services')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='vynzora_app.services')),
            ],
        ),
        migrations.CreateModel(
            name='TrainFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('train_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='vynzora_app.trainservice')),
            ],
            options={
                'verbose_name': 'Train FAQ',
                'verbose_name_plural': 'Train FAQs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='vynzora_app.website')),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
